core/urls.py
from django.urls import path
from .views import *

app_name="core"

urlpatterns = [
    path("user-profile/<int:pk>/", user_profile_view, name="user-profile"),
    path("projects/<int:pk>/", detail_project_view, name="detail-project"),
    path("add-project/", add_project_view, name="add-project"),
    path("profile-update/", profile_update_view, name="profile-update"),
    path("my-profile/", my_profile_view, name="my-profile"),
    path("", home_view, name="home"),
]

devpro/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),

    path("accounts/", include('django.contrib.auth.urls')),
    
    path("accounts/", include('users.urls')),
    path("", include('core.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name="users"

urlpatterns =[
    path("update_user/", update_user_view, name="update-user"),
    path("logout_user/", logout_view, name="logout-user"),
    path("", signup_view, name="signup"),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from projects.models import *

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            "bio", "profession", "tech_stack", "profile_photo", 
        ]

        widgets = {
            "profession": forms.CheckboxSelectMultiple,
            "tech_stack": forms.CheckboxSelectMultiple,
        }

class ProjectForm(forms.ModelForm):
    class Meta:
        model=Project
        fields=[
            "name", "description","technology_used", "pro_image","demo_link", "github_link",
        ]
        widgets = {
            "technology_used": forms.CheckboxSelectMultiple,
        }
        

core/views.py
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.db.models import Q


from projects.models import *
from .forms import *

CustomUser=get_user_model()

@login_required
def home_view(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    #followers for my profile
    followers= Follow.objects.filter(profile=profile)
    #the profiles that the  user is following
    following = Follow.objects.filter(follower=user)

    #list of users folliwing me
    my_followers = []
    for my_follower in followers:
        my_followers.append(my_follower.follower)

    #list of profiles i am following
    my_followings = []
    for my_following in following:
        my_followings.append(my_following.profile)

    projects = Project.objects.filter(Q(profile__user__in = my_followers)| Q(profile__in = my_followings)|Q(profile=profile))
    context = {
        "projects":projects,
    }
    return render(request, "core/home.html", context)

@login_required
def my_profile_view(request):
    user = request.user
    user_profile = get_object_or_404(Profile, user=user)
    followers= Follow.objects.filter(profile=user_profile)
    following = Follow.objects.filter(follower=user)

    if followers:
        profile_followers= followers.count
    else:
        profile_followers=0

    if following:
        profile_following= following.count
    else:
        profile_following=0
    context={
        "profile":user_profile,
        "followers": profile_followers,
        "following":profile_following,
    }
    return render(request, "core/my_profile.html", context)

@login_required
def user_profile_view(request, pk):
    user = request.user

    requested_profile = get_object_or_404(Profile, id=pk)
    requested_profile_user = get_object_or_404(CustomUser, profile=requested_profile)

    #followers for requested profile
    followers= Follow.objects.filter(profile=requested_profile)
    #the profiles that the requested user is folloewing
    following = Follow.objects.filter(follower=requested_profile_user)

    #the profiles that the current logged in user is following
    logged_in_user_following = Follow.objects.filter(follower=user)
    

    flw=[]

    for followedprofile in logged_in_user_following:
        flw.append(followedprofile.profile)

    #btn follow unfollow text
    if requested_profile in flw:
            btn_text = 'UNFOLLOW'
            
    else:
            btn_text='FOLLOW'

    #follow/unfollowing
    if request.method == 'POST':
        if requested_profile in flw:
            followed_profile = Follow.objects.get(follower=user, profile=requested_profile)
            followed_profile.delete()
            
        else:
            new_followed_profile = Follow.objects.create(follower=user, profile=requested_profile)
            new_followed_profile.save()
            
        return redirect(f"/user-profile/{pk}/")
      

    if followers:
        profile_followers= followers.count
    else:
        profile_followers=0

    if following:
        profile_following= following.count
    else:
        profile_following=0

    context={
        "profile":requested_profile,
        "followers": profile_followers,
        "following":profile_following,
        "btn_text":btn_text,
    }
    return render(request, "core/user_profile.html", context)



@login_required
def profile_update_view(request):   
    user = request.user
    user_profile = get_object_or_404(Profile, user=user)
    if request.method=='POST':
        form = ProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect("core:my-profile")

    else:
        form = ProfileForm(instance=user_profile)

    context = {
        "form":form,
    }
    return render(request, "core/update_profile.html", context)

@login_required
def add_project_view(request):
    user = request.user
    user_profile = get_object_or_404(Profile, user=user)
    
    if request.method=='POST':
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            project = form.save(commit=False)
            project.profile=user_profile
            project.save()
            return redirect("core:home")

    else:
        form= ProjectForm()

    context = {
        "form":form,
    }
    return render(request, "core/add_project.html", context)

@login_required
def detail_project_view(request, pk):
    project = get_object_or_404(Project, id=pk)
    context = {
        "project":project,
    }

    return render(request, "core/detail_project.html", context)

core/templates/core/add_project.html
{% extends 'core/base.html'%}
{% block title %} Add project{% endblock title%}

{% block content %}
<section>
    <h2>Add Project</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">POST</button>
    </form>
</section>
{% endblock content%}

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title%} | DEVSHOWCASE</title>
</head>
<body>
    <nav>
        
        <ul>
            <li><a href="{% url 'core:home' %}">Home</a></li>
            <li><a href="{% url 'users:logout-user' %}">LOGOUT</a></li>
            <li><a href="{% url 'users:update-user' %}">Update Personal info</a></li>
            <li><a href="{% url 'core:profile-update' %}">Update Profile Info</a></li>
            <li><a href="{% url 'core:my-profile' %}">My Profile</a></li>
            <li><a href="{% url 'core:add-project' %}">Add Project</a></li>
            <li><a href="">Search Project</a></li>
        </ul>
    </nav>
    <main>
        <section>
            <div>
                <p>Recommended Accounts</p>
            </div>
        </section>
        <section>
            {% block content %}
            {% endblock content%}
        </section>
      
    </main>
</body>
</html>

core/templates/core/detail_project.html
{% extends 'core/base.html'%}
{% block title %} Project Detail{% endblock title%}

{% block content %}
<section>
    <div>
        <h2>Project Detail</h2>
        
        <div>
            <h3>{{project.name}}</h3>
            <img src="{{project.pro_image.url}}" alt="Project Image">
            <p>{{project.description}}</p>
            {% for tech in project.technology_used.all %}
            <p>{{tech}}</p>
            {%endfor%}
            <p><a href="{{project.demo_link}}">Live Demo</a></p>
            <p><a href="{{project.github_link}}">Github Repo</a</p>
        </div>
        <button><a href="">Edit</a></button>
        <button><a href="">Delete</a></button>
    </div>
</section>
{% endblock content%}

core/templates/core/home.html
{% extends 'core/base.html'%}
{% block title %} HOME{% endblock title%}

{% block content %}
<section>
    <h2>Welcome {{user.first_name}} {{user.last_name}} to DevShowCase</h2>
    <h3>Feed</h3>
    {% for project in projects%}
    <div>
        <p><a href="{% url 'core:user-profile' project.profile.id %}">{{project.profile.user.username}}</a></p>
        <img src="{{project.pro_image.url}}" alt="Project Image">
        <p>{{project.name}}</p>
        <p>{{project.description}}</p>
        <hr>
    </div>
    {% empty %}
    <h2>No feeds</h2>

    {% endfor %}
</section>
{% endblock content%}

core/templates/core/my_profile.html
{% extends 'core/base.html'%}
{% block title %} Profile{% endblock title%}

{% block content %}
<section>
    <div>
        <h2>Profile Details</h2>
        <h3>Followers:</h3>
        <p>{{followers}}</p>

        <h3>Following:</h3>
        <p>{{following}}</p>
        
        <h2>Profile Picture:</h2>
        <img src="{{profile.profile_photo.url}}" alt="ProfilePic">
        <h3>Bio:</h3>
        <p>{{profile.bio}}</p>
        <h3>Tech Stack:</h3>
        {% for tech in profile.tech_stack.all %}
        <p>{{tech.name}}</p>
        {%endfor%}
        <h3>Profession:</h3>
        {% for profession in profile.profession.all %}
        <p>{{profession.name}}</p>
        {%endfor%}
    </div>
    <div>
        <h2>Projects</h2>
        {% for project in profile.projects.all %}
            <div>
                <p><a href="{% url 'core:detail-project' project.id %}">{{project.name}}</a></p>
                <img src="{{project.pro_image.url}}" alt="">

            </div>
        {%empty%}
        <h2>No projects</h2>
        {%endfor%}
    </div>
</section>
{% endblock content%}

core/templates/core/update_profile.html
{% extends 'core/base.html'%}
{% block title %} Update Profile{% endblock title%}

{% block content %}
<section>
    <h2>Update Profile Info</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Update</button>
    </form>
</section>
{% endblock content%}

core/templates/core/user_profile.html
{% extends 'core/base.html'%}
{% block title %} Profile{% endblock title%}

{% block content %}
<section>
    <div>
        <h2>Profile Details</h2>
       {% if request.user != profile.user%}
        <div>
            <form method="post">
                {% csrf_token %}
                <button type="submit">{{btn_text}}</button>
            </form>
        </div>
        {%endif%}
        <h3>Followers:</h3>
        <p>{{followers}}</p>

        <h3>Following:</h3>
        <p>{{following}}</p>
        
        <h2>Profile Picture:</h2>
        <img src="{{profile.profile_photo.url}}" alt="ProfilePic">
        <h3>Bio:</h3>
        <p>{{profile.bio}}</p>
        <h3>Tech Stack:</h3>
        {% for tech in profile.tech_stack.all %}
        <p>{{tech.name}}</p>
        {%endfor%}
        <h3>Profession:</h3>
        {% for profession in profile.profession.all %}
        <p>{{profession.name}}</p>
        {%endfor%}
    </div>
    <div>
        <h2>Projects</h2>
        {% for project in profile.projects.all %}
            <div>
                <p>{{project.name}}</p>
                <img src="{{project.pro_image.url}}" alt="">

            </div>
        {%empty%}
        <h2>No projects</h2>
        {%endfor%}
    </div>
</section>
{% endblock content%}